# Generated by Django 2.1.7 on 2019-02-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='English', help_text='Enter the language of the book', max_length=50, verbose_name='Language'),
        ),
    ]
